apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
      - name: dotnetapp
        image: 381492032511.dkr.ecr.us-east-1.amazonaws.com/dotnetapp:v3
        ports:
        - containerPort: 8080
        env:
        - name: DbConnectionString
          valueFrom:
            secretKeyRef:
              name: dotnet-secret
              key: DbConnectionString