apiVersion: v1
kind: Secret
metadata:
  name: dotnet-secret
type: Opaque
data:
  DbConnectionString: U2VydmVyPWNsb3VkbmF0aXZlc3YtZGV2LmNoODY0dXlzNmtsci51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20sMTQzMztEYXRhYmFzZT1kYlRvZG87VXNlciBJZD1hZG1pbjtQYXNzd29yZD1DUzVFcUUoIUJxVjp4JGZ9NThkWXchSSp5e0dUO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZTsK
  